apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ek11fiiha-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:fc1f3141e27c15569e90969c4eb2631ef604bb66@sha256:de6f5613a2f5578a95958d99d8da74f2afb3aa57c0c6bd4242e4c5a7f7b66a72
          name: container-image
