apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ek11fiiha-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ek11fiiha-go 
  name: ek11fiiha-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ek11fiiha-go 
